source 'https://rubygems.org'

gemspec

# Compass for the dummy app
gem 'compass', require: false

# Gems for Bootstrap
gem autoprefixer-rails
gem jekyll-assets

group :development do
  gem 'byebug', platforms: [:mri_21, :mri_22], require: false
end
